version: '3.9'
services:
  user-database:
    image: postgres:14.2
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-test}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
      POSTGRES_DB: "user"

  user-service:
    depends_on:
      - user-database
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "8081:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ENABLE_SWAGGER: true

networks:
  default:
    name: twiddit
